// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Scanner.flex

import java.io.*;

/* ------------ Jflex Options ------------ */
// JFLEX OPTIONS

@SuppressWarnings("fallthrough")
public class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\4\1\5"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\10\12\22\1\23"+
    "\1\24\1\5\1\25\1\5\2\0\4\26\1\27\25\26"+
    "\1\30\1\31\1\32\1\0\1\33\1\0\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\42"+
    "\1\45\1\46\1\42\1\47\1\50\1\51\1\42\1\52"+
    "\1\53\1\54\1\55\5\42\1\56\1\57\1\60\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\6\2\1\1\10\1\11\2\6\1\12\1\6"+
    "\1\7\1\13\1\14\1\15\1\16\1\17\1\20\14\21"+
    "\1\22\1\1\1\23\1\0\1\24\1\0\1\25\4\0"+
    "\1\16\15\21\1\0\1\26\1\27\1\16\14\21\1\30"+
    "\1\27\1\0\1\16\4\21\1\31\5\21\1\32\1\27"+
    "\1\0\1\27\1\16\2\21\1\33\3\21\1\27\1\16"+
    "\2\21\1\27\1\16\1\27\1\16\1\34\1\16\1\0"+
    "\1\16\1\0\1\34\25\16\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\61\0\61\0\61\0\142\0\223"+
    "\0\304\0\61\0\365\0\u0126\0\61\0\61\0\u0157\0\u0188"+
    "\0\61\0\u01b9\0\61\0\u01ea\0\61\0\61\0\u021b\0\61"+
    "\0\61\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\61\0\u0498\0\61"+
    "\0\223\0\61\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746"+
    "\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\61"+
    "\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\61\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\u024c\0\u0cd3"+
    "\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u024c\0\u0dc8\0\u0df9\0\u0df9"+
    "\0\u0e2a\0\u0e5b\0\u0e8c\0\u024c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50"+
    "\0\u0f81\0\u0fb2\0\u0fe3\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8"+
    "\0\u1109\0\u113a\0\u116b\0\u119c\0\u119c\0\u11cd\0\u11fe\0\u122f"+
    "\0\u1260\0\u1291\0\u12c2\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7"+
    "\0\u13e8\0\u1419\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f"+
    "\0\u1570\0\u15a1\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\7\2\27\1\30"+
    "\1\2\1\31\1\23\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\32\1\40\1\32\1\41\1\32\1\42\1\32"+
    "\1\43\1\44\1\45\1\32\1\46\1\47\1\50\106\0"+
    "\1\12\33\0\2\51\1\0\3\51\1\52\22\51\1\53"+
    "\27\51\7\0\1\54\5\0\1\55\54\0\1\12\47\0"+
    "\2\56\1\0\7\56\1\0\16\56\1\57\27\56\15\0"+
    "\1\12\7\0\1\12\51\0\1\12\3\0\1\24\2\0"+
    "\1\12\53\0\1\12\1\0\1\24\2\0\1\12\54\0"+
    "\1\60\1\24\60\0\1\61\10\0\23\61\25\0\1\32"+
    "\10\0\23\32\25\0\1\32\10\0\17\32\1\62\3\32"+
    "\25\0\1\32\10\0\15\32\1\63\5\32\25\0\1\32"+
    "\10\0\5\32\1\64\15\32\25\0\1\32\10\0\13\32"+
    "\1\65\7\32\25\0\1\32\10\0\1\32\1\66\7\32"+
    "\1\67\10\32\1\70\25\0\1\32\10\0\14\32\1\71"+
    "\6\32\25\0\1\32\10\0\15\32\1\72\5\32\25\0"+
    "\1\32\10\0\22\32\1\73\25\0\1\32\10\0\5\32"+
    "\1\74\15\32\25\0\1\32\10\0\21\32\1\75\1\32"+
    "\25\0\1\32\10\0\17\32\1\76\3\32\62\0\1\12"+
    "\7\0\1\51\22\0\1\51\15\0\1\51\2\0\1\51"+
    "\1\0\1\51\4\0\2\54\1\0\56\54\15\55\1\77"+
    "\43\55\12\0\1\100\60\0\1\56\16\0\1\56\15\0"+
    "\1\56\2\0\1\56\1\0\1\56\26\0\1\101\60\0"+
    "\1\102\10\0\23\102\25\0\1\32\10\0\5\32\1\103"+
    "\15\32\25\0\1\32\10\0\14\32\1\104\6\32\25\0"+
    "\1\32\10\0\3\32\1\105\17\32\25\0\1\32\10\0"+
    "\20\32\1\106\2\32\25\0\1\32\10\0\13\32\1\107"+
    "\7\32\25\0\1\32\10\0\14\32\1\110\6\32\25\0"+
    "\1\32\10\0\14\32\1\111\6\32\25\0\1\32\10\0"+
    "\16\32\1\112\4\32\25\0\1\32\10\0\15\32\1\113"+
    "\5\32\25\0\1\32\10\0\21\32\1\71\1\32\25\0"+
    "\1\32\10\0\21\32\1\114\1\32\25\0\1\32\10\0"+
    "\1\32\1\115\21\32\25\0\1\32\10\0\22\32\1\116"+
    "\3\0\7\55\1\117\5\55\1\77\43\55\22\0\1\120"+
    "\4\0\1\121\10\0\1\121\42\0\1\122\10\0\23\122"+
    "\25\0\1\32\10\0\1\32\1\123\21\32\25\0\1\32"+
    "\10\0\4\32\1\124\14\32\1\125\1\32\25\0\1\32"+
    "\10\0\13\32\1\126\7\32\25\0\1\32\10\0\5\32"+
    "\1\127\15\32\25\0\1\32\10\0\20\32\1\130\2\32"+
    "\25\0\1\32\10\0\11\32\1\131\11\32\25\0\1\32"+
    "\10\0\3\32\1\132\17\32\25\0\1\32\10\0\22\32"+
    "\1\133\25\0\1\32\10\0\16\32\1\127\4\32\25\0"+
    "\1\32\10\0\22\32\1\134\25\0\1\32\10\0\17\32"+
    "\1\133\3\32\25\0\1\32\10\0\5\32\1\135\15\32"+
    "\25\0\1\136\4\0\1\121\10\0\1\121\36\0\1\137"+
    "\1\0\1\137\1\0\1\140\60\0\1\141\10\0\23\141"+
    "\25\0\1\32\10\0\12\32\1\127\10\32\25\0\1\32"+
    "\10\0\11\32\1\132\11\32\25\0\1\32\10\0\11\32"+
    "\1\142\11\32\25\0\1\32\10\0\1\32\1\143\21\32"+
    "\25\0\1\32\10\0\5\32\1\144\15\32\25\0\1\32"+
    "\10\0\20\32\1\145\2\32\25\0\1\32\10\0\21\32"+
    "\1\146\1\32\25\0\1\32\10\0\21\32\1\127\1\32"+
    "\25\0\1\32\10\0\17\32\1\147\3\32\25\0\1\150"+
    "\4\0\1\121\10\0\1\121\42\0\1\140\60\0\1\151"+
    "\10\0\23\151\25\0\1\32\10\0\14\32\1\152\6\32"+
    "\25\0\1\32\10\0\17\32\1\106\3\32\25\0\1\32"+
    "\10\0\10\32\1\127\12\32\25\0\1\32\10\0\11\32"+
    "\1\153\11\32\25\0\1\32\10\0\14\32\1\127\6\32"+
    "\25\0\1\154\4\0\1\121\10\0\1\121\42\0\1\155"+
    "\10\0\23\155\25\0\1\32\10\0\22\32\1\106\25\0"+
    "\1\32\10\0\15\32\1\147\5\32\25\0\1\156\4\0"+
    "\1\121\10\0\1\121\42\0\1\157\10\0\23\157\25\0"+
    "\1\160\4\0\1\121\10\0\1\121\42\0\1\161\10\0"+
    "\23\161\32\0\1\162\10\0\1\162\42\0\1\163\10\0"+
    "\23\163\21\0\1\164\1\0\1\164\1\0\1\165\60\0"+
    "\1\166\10\0\23\166\25\0\1\165\60\0\1\167\10\0"+
    "\23\167\25\0\1\170\10\0\23\170\25\0\1\171\10\0"+
    "\23\171\25\0\1\172\10\0\23\172\25\0\1\173\10\0"+
    "\23\173\25\0\1\174\10\0\23\174\25\0\1\175\10\0"+
    "\23\175\25\0\1\176\10\0\23\176\25\0\1\177\10\0"+
    "\23\177\25\0\1\200\10\0\23\200\25\0\1\201\10\0"+
    "\23\201\25\0\1\202\10\0\23\202\25\0\1\203\10\0"+
    "\23\203\25\0\1\204\10\0\23\204\25\0\1\205\10\0"+
    "\23\205\25\0\1\206\10\0\23\206\25\0\1\207\10\0"+
    "\23\207\25\0\1\210\10\0\23\210\25\0\1\211\10\0"+
    "\23\211\25\0\1\212\10\0\23\212\25\0\1\213\10\0"+
    "\23\213\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5586];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\5\11\3\1\1\11\2\1\2\11\2\1\1\11"+
    "\1\1\1\11\1\1\2\11\1\1\2\11\14\1\1\11"+
    "\1\1\1\11\1\0\1\11\1\0\1\1\4\0\16\1"+
    "\1\0\1\11\16\1\1\11\1\1\1\0\15\1\1\0"+
    "\22\1\1\0\1\1\1\0\26\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private int tokenCount = 0;
    private ErrorHandler eh = new ErrorHandler();
    public int getTokenCount() {
        return tokenCount;
    }
    private Token returnToken(TokenType ttype) {
        return new Token(ttype, yytext().toString(), yyline + 1, yycolumn + 1);
    }
    private Token returnToken(TokenType ttype, String text) {
        return new Token(ttype, text, yyline + 1, yycolumn + 1);
    }

    public ErrorHandler getErrorHandler() {
        return eh;
    }
    private void reportError(String reason) {
        eh.insert("Lexical Error", yyline + 1, yycolumn + 1, reason);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return returnToken(TokenType.EOF, null);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { tokenCount++;
    reportError("Character " + yytext() + " does not belong to the language");
    return returnToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 30: break;
          case 2:
            { tokenCount++; return returnToken(TokenType.TAB, "\\t");
            }
          // fall through
          case 31: break;
          case 3:
            { tokenCount++; return returnToken(TokenType.NEWLINE, "\\n");
            }
          // fall through
          case 32: break;
          case 4:
            { tokenCount++; return returnToken(TokenType.CARRIAGE_RETURN, "\\r");
            }
          // fall through
          case 33: break;
          case 5:
            { tokenCount++; return returnToken(TokenType.SPACE);
            }
          // fall through
          case 34: break;
          case 6:
            { tokenCount++; return returnToken(TokenType.OPERATOR);
            }
          // fall through
          case 35: break;
          case 7:
            { //System.out.println("WARNING! Unrecognized character at Line: " + (yyline + 1) + ", Col: " + (yycolumn + 1) + " : " + yytext());
          reportError("Unrecognized character: " + yytext());
          return returnToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 36: break;
          case 8:
            { tokenCount++; return returnToken(TokenType.L_ROUND_BRACKET);
            }
          // fall through
          case 37: break;
          case 9:
            { tokenCount++; return returnToken(TokenType.R_ROUND_BRACKET);
            }
          // fall through
          case 38: break;
          case 10:
            { tokenCount++; return returnToken(TokenType.COMMA);
            }
          // fall through
          case 39: break;
          case 11:
            { tokenCount++; return returnToken(TokenType.INT_LITERAL);
            }
          // fall through
          case 40: break;
          case 12:
            { tokenCount++; return returnToken(TokenType.COLON);
            }
          // fall through
          case 41: break;
          case 13:
            { tokenCount++; return returnToken(TokenType.SEMICOLON);
            }
          // fall through
          case 42: break;
          case 14:
            { tokenCount++; return returnToken(TokenType.IDENTIFIER);
            }
          // fall through
          case 43: break;
          case 15:
            { tokenCount++; return returnToken(TokenType.L_SQUARE_BRACKET);
            }
          // fall through
          case 44: break;
          case 16:
            { tokenCount++; return returnToken(TokenType.R_SQUARE_BRACKET);
            }
          // fall through
          case 45: break;
          case 17:
            { tokenCount++;
    reportError("Violation of Rule, no token either start or contain " + yytext().substring(0,1));
    return returnToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 46: break;
          case 18:
            { tokenCount++; return returnToken(TokenType.L_CURLY_BRACKET);
            }
          // fall through
          case 47: break;
          case 19:
            { tokenCount++; return returnToken(TokenType.R_CURLY_BRACKET);
            }
          // fall through
          case 48: break;
          case 20:
            { tokenCount++; return returnToken(TokenType.STRING_LITERAL);
            }
          // fall through
          case 49: break;
          case 21:
            { tokenCount++; return returnToken(TokenType.SINGLE_LINE_COMMENT, yytext().replace('\r',' '));
            }
          // fall through
          case 50: break;
          case 22:
            { tokenCount++; return returnToken(TokenType.CHAR_LITERAL);
            }
          // fall through
          case 51: break;
          case 23:
            { tokenCount++; return returnToken(TokenType.FLOAT_LITERAL);
            }
          // fall through
          case 52: break;
          case 24:
            { tokenCount++; return returnToken(TokenType.MULTI_LINE_COMMENT, "#*...*#");
            }
          // fall through
          case 53: break;
          case 25:
            { tokenCount++; return returnToken(TokenType.KEYWORD);
            }
          // fall through
          case 54: break;
          case 26:
            { tokenCount++; return returnToken(TokenType.TRUE_BOOL);
            }
          // fall through
          case 55: break;
          case 27:
            { tokenCount++; return returnToken(TokenType.FALSE_BOOL);
            }
          // fall through
          case 56: break;
          case 28:
            { tokenCount++;
    reportError("Maximum 6 characters allowed after Decimal Point in Float");
    return returnToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 57: break;
          case 29:
            { tokenCount++;
    reportError("Maximum 31 characters allowed in Identifier Name");
    return returnToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
